# Generated by Django 2.1.1 on 2018-09-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180919_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avilable',
            new_name='available',
        ),
    ]
